default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 10

development:
  <<: *default
  database: surfcast_development

test:
  <<: *default
  database: surfcast_test

production:
  <<: *default
  database: surfcast_production
